### ISSUE TITLE
Spring Boot Auto Configuration not usable in WebFlux project

### ISSUE THREAD

**Issue by jrehwaldt** [zalando/tracer#154]
Currently, when including `org.zalando:tracer-spring-boot-starter` into Spring 5 reactive applications Spring cannot start (`NoClassDefFoundError: javax/servlet/Filter`) because of `TracerAutoConfiguration`'s hard dependency on `javax.servlet.Filter`.

```
Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.zalando.tracer.spring.TracerAutoConfiguration] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:659)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:556)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:541)
	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:726)
        ....
Caused by: java.lang.NoClassDefFoundError: javax/servlet/Filter
```

## Expected Behavior
The application should start, but disable servlet filtering. All other configurations should be preserved.

## Actual Behavior
It fails.

## Possible Fix
Extract `TracerFilterAutoConfiguration` into separate class and add `@ConditionalOnWebApplication` there.

**Comment by whiskeysierra** [comment]
Thanks for reporting! Your proposal would fix it, but we wouldn't have proper support for Spring WebFlux afterwards. We have a similar discussion in https://github.com/zalando/logbook/issues/331.

**Comment by jrehwaldt** [comment]
I know. But at least all other configuration properties such as MDCListener etc would work as expected. All else might or might not be added in the future.

**Comment by whiskeysierra** [comment]
Yes, makes sense. Would you be willing to open a pull request by any chance?

**Comment by jrehwaldt** [comment]
I'll have a look next week.
